/**
 * 테마 목록과 표시 이름 매핑
 * fetch-themes.js 스크립트로 다운로드한 테마 목록
 */

export const themeList = [
  { value: "default", label: "기본" },
  { value: "amber-minimal", label: "Amber Minimal" },
  { value: "amethyst-haze", label: "Amethyst Haze" },
  { value: "bold-tech", label: "Bold Tech" },
  { value: "bubblegum", label: "Bubblegum" },
  { value: "caffeine", label: "Caffeine" },
  { value: "candyland", label: "Candyland" },
  { value: "catppuccin", label: "Catppuccin" },
  { value: "claude", label: "Claude" },
  { value: "claymorphism", label: "Claymorphism" },
  { value: "clean-slate", label: "Clean Slate" },
  { value: "cosmic-night", label: "Cosmic Night" },
  { value: "cyberpunk", label: "Cyberpunk" },
  { value: "darkmatter", label: "Darkmatter" },
  { value: "doom-64", label: "Doom 64" },
  { value: "elegant-luxury", label: "Elegant Luxury" },
  { value: "graphite", label: "Graphite" },
  { value: "kodama-grove", label: "Kodama Grove" },
  { value: "midnight-bloom", label: "Midnight Bloom" },
  { value: "mocha-mousse", label: "Mocha Mousse" },
  { value: "modern-minimal", label: "Modern Minimal" },
  { value: "mono", label: "Mono" },
  { value: "nature", label: "Nature" },
  { value: "neo-brutalism", label: "Neo Brutalism" },
  { value: "northern-lights", label: "Northern Lights" },
  { value: "notebook", label: "Notebook" },
  { value: "ocean-breeze", label: "Ocean Breeze" },
  { value: "pastel-dreams", label: "Pastel Dreams" },
  { value: "perpetuity", label: "Perpetuity" },
  { value: "quantum-rose", label: "Quantum Rose" },
  { value: "retro-arcade", label: "Retro Arcade" },
  { value: "soft-pop", label: "Soft Pop" },
  { value: "solar-dusk", label: "Solar Dusk" },
  { value: "starry-night", label: "Starry Night" },
  { value: "sunset-horizon", label: "Sunset Horizon" },
  { value: "supabase", label: "Supabase" },
  { value: "t3-chat", label: "T3 Chat" },
  { value: "tangerine", label: "Tangerine" },
  { value: "twitter", label: "Twitter" },
  { value: "vercel", label: "Vercel" },
  { value: "vintage-paper", label: "Vintage Paper" },
  { value: "violet-bloom", label: "Violet Bloom" },
];
